# Generated by Django 4.2.7 on 2024-01-14 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cc', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_cc', models.CharField(max_length=10)),
                ('nombre_cc', models.CharField(max_length=150)),
                ('correo_cc', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_cc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cc', models.CharField(max_length=150)),
                ('tipo_cc', models.CharField(max_length=150)),
                ('foto_cc', models.FileField(blank=True, null=True, upload_to='ingredientes')),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id_cc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cc', models.CharField(max_length=150)),
                ('porciones_cc', models.CharField(max_length=150)),
                ('foto_cc', models.FileField(blank=True, null=True, upload_to='platillos')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_cc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cc', models.CharField(max_length=150)),
                ('codigo_cc', models.IntegerField()),
                ('foto_cc', models.FileField(blank=True, null=True, upload_to='banderas')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_cc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cc', models.CharField(max_length=150)),
                ('origen_cc', models.CharField(max_length=150)),
                ('descripcion_cc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_cc', models.AutoField(primary_key=True, serialize=False)),
                ('tiempo_cc', models.CharField(max_length=150)),
                ('origen_cc', models.CharField(max_length=150)),
                ('indicaciones_cc', models.TextField()),
                ('ingrediente_cc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FacturacionCC.ingrediente')),
                ('platillo_cc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FacturacionCC.platillo')),
            ],
        ),
        migrations.AddField(
            model_name='platillo',
            name='tipo_cc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FacturacionCC.tipo'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_cc', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cc', models.DateTimeField()),
                ('tipopago_cc', models.CharField(max_length=150)),
                ('servicio_cc', models.CharField(max_length=150)),
                ('cliente_cc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FacturacionCC.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id_cc', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_cc', models.PositiveIntegerField()),
                ('costou_cc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costot_cc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido_cc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FacturacionCC.pedido')),
                ('platillo_cc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FacturacionCC.platillo')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia_cc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FacturacionCC.provincia'),
        ),
    ]
