# Generated by Django 4.2.7 on 2024-01-14 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacturacionCC', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo',
            old_name='origen_cc',
            new_name='dificultad_cc',
        ),
    ]
