# Generated by Django 4.2.7 on 2024-01-16 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacturacionCC', '0003_remove_detalle_costou_cc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle',
            old_name='cantidad_cc',
            new_name='mesa_cc',
        ),
    ]
